# CP-10 - End-to-end latency validation for alerts generated by valid transactions
# Sends 20 valid HIGH_AMOUNT transactions, reads alerts, correlates by source_transaction_id,
# and calculates latency using: latency_ms = (triggered_at - produced_at_epoch) * 1000.

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $repoRoot

$evidenceDir = Join-Path $repoRoot "docs\evidence"

$terminalLogPath = Join-Path $evidenceDir "cp10_terminal_log.txt"
$inputEventsPath = Join-Path $evidenceDir "cp10_input_events.txt"
$producerOutputLogPath = Join-Path $evidenceDir "cp10_producer_output_log.txt"
$alertsValidationLogPath = Join-Path $evidenceDir "cp10_alerts_validation_log.txt"
$latencyResultsPath = Join-Path $evidenceDir "cp10_latency_results.csv"
$latencySummaryPath = Join-Path $evidenceDir "cp10_latency_summary.txt"

$topicInput = "transactions-online"
$topicAlerts = "alerts"

$sampleCount = 20
$amount = "20000.00"
$currency = "USD"
$latencyThresholdMs = 3000

function Add-TerminalLog {
    param (
        [AllowEmptyString()]
        [string]$Message
    )

    $Message | Add-Content -LiteralPath $terminalLogPath -Encoding UTF8
}

function Invoke-ProcessWithOptionalInput {
    param (
        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [string]$InputText = $null
    )

    $processInfo = New-Object System.Diagnostics.ProcessStartInfo
    $processInfo.FileName = $FilePath
    $processInfo.WorkingDirectory = $repoRoot
    $processInfo.UseShellExecute = $false
    $processInfo.RedirectStandardOutput = $true
    $processInfo.RedirectStandardError = $true
    $processInfo.CreateNoWindow = $true

    if ($null -ne $InputText) {
        $processInfo.RedirectStandardInput = $true
    }

    $escapedArgs = $Arguments | ForEach-Object {
        if ($_ -match '\s|"' ) {
            '"' + ($_ -replace '"', '\"') + '"'
        }
        else {
            $_
        }
    }

    $processInfo.Arguments = ($escapedArgs -join " ")

    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $processInfo

    [void]$process.Start()

    if ($null -ne $InputText) {
        $process.StandardInput.WriteLine($InputText)
        $process.StandardInput.Close()
    }

    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()

    $process.WaitForExit()

    return [PSCustomObject]@{
        ExitCode = $process.ExitCode
        Stdout = $stdout
        Stderr = $stderr
    }
}

"CP-10 - End-to-end latency validation for HIGH_AMOUNT alerts" | Set-Content -LiteralPath $terminalLogPath -Encoding UTF8
"" | Set-Content -LiteralPath $inputEventsPath -Encoding UTF8
"" | Set-Content -LiteralPath $producerOutputLogPath -Encoding UTF8
"" | Set-Content -LiteralPath $alertsValidationLogPath -Encoding UTF8
"" | Set-Content -LiteralPath $latencyResultsPath -Encoding UTF8
"" | Set-Content -LiteralPath $latencySummaryPath -Encoding UTF8

Write-Host "CP-10 - End-to-end latency validation for HIGH_AMOUNT alerts"
Write-Host "Repository root: $repoRoot"
Write-Host ""

Add-TerminalLog "Execution date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Add-TerminalLog "Repository root: $repoRoot"
Add-TerminalLog ""
Add-TerminalLog "Objective:"
Add-TerminalLog "Validate that valid HIGH_AMOUNT transactions generate alerts with average end-to-end latency below $latencyThresholdMs ms."
Add-TerminalLog ""
Add-TerminalLog "Measurement:"
Add-TerminalLog "latency_ms = (triggered_at - produced_at_epoch) * 1000"
Add-TerminalLog ""
Add-TerminalLog "Configuration:"
Add-TerminalLog "Samples: $sampleCount"
Add-TerminalLog "Input topic: $topicInput"
Add-TerminalLog "Alerts topic: $topicAlerts"
Add-TerminalLog "Amount: $amount"
Add-TerminalLog "Currency: $currency"
Add-TerminalLog ""

Write-Host "Starting services required for CP-10..."

$composeResult = Invoke-ProcessWithOptionalInput `
    -FilePath "docker" `
    -Arguments @(
        "compose",
        "up",
        "-d",
        "kafka",
        "kafka-ui",
        "flink-jobmanager",
        "flink-taskmanager",
        "flink-anomalies-job"
    )

Add-TerminalLog "Command executed:"
Add-TerminalLog "docker compose up -d kafka kafka-ui flink-jobmanager flink-taskmanager flink-anomalies-job"
Add-TerminalLog ""
Add-TerminalLog $composeResult.Stdout
Add-TerminalLog $composeResult.Stderr

if ($composeResult.ExitCode -ne 0) {
    throw "docker compose command failed with exit code $($composeResult.ExitCode)."
}

Write-Host "Waiting for services and anomalies job to be ready..."
Start-Sleep -Seconds 45

Write-Host "Generating and publishing $sampleCount HIGH_AMOUNT events..."

for ($i = 1; $i -le $sampleCount; $i++) {
    $transactionId = "cp10-latency-{0:D3}" -f $i
    $cardId = "4532015112831{0:D3}" -f $i
    $now = [DateTimeOffset]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.ffffffzzz")

    $line = "$cardId|{`"transaction_id`":`"$transactionId`",`"card_id`":`"$cardId`",`"event_timestamp`":`"$now`",`"produced_at`":`"$now`",`"channel`":`"ONLINE`",`"amount`":20000.00,`"currency`":`"$currency`",`"status`":`"APPROVED`",`"merchant_name`":`"CP10 Test Merchant`",`"merchant_category`":`"electronics`",`"city`":`"Bogota`",`"country`":`"CO`"}"

    $line | Add-Content -LiteralPath $inputEventsPath -Encoding UTF8

    $producerResult = Invoke-ProcessWithOptionalInput `
        -FilePath "docker" `
        -Arguments @(
            "exec",
            "-i",
            "kafka",
            "kafka-console-producer.sh",
            "--bootstrap-server",
            "localhost:9094",
            "--topic",
            $topicInput,
            "--property",
            "parse.key=true",
            "--property",
            "key.separator=|"
        ) `
        -InputText $line

    "Event $transactionId producer stdout:" | Add-Content -LiteralPath $producerOutputLogPath -Encoding UTF8
    $producerResult.Stdout | Add-Content -LiteralPath $producerOutputLogPath -Encoding UTF8
    "Event $transactionId producer stderr:" | Add-Content -LiteralPath $producerOutputLogPath -Encoding UTF8
    $producerResult.Stderr | Add-Content -LiteralPath $producerOutputLogPath -Encoding UTF8
    "" | Add-Content -LiteralPath $producerOutputLogPath -Encoding UTF8

    if ($producerResult.ExitCode -ne 0) {
        throw "Kafka producer command failed with exit code $($producerResult.ExitCode). Check log: $producerOutputLogPath"
    }

    Start-Sleep -Milliseconds 100
}

Add-TerminalLog "Input events written to:"
Add-TerminalLog $inputEventsPath
Add-TerminalLog ""
Add-TerminalLog "Producer command executed successfully."
Add-TerminalLog "Producer output log:"
Add-TerminalLog $producerOutputLogPath
Add-TerminalLog ""

Write-Host "Waiting for alerts to be generated..."
Start-Sleep -Seconds 15

Write-Host "Consuming alerts from $topicAlerts..."

$alertsResult = Invoke-ProcessWithOptionalInput `
    -FilePath "docker" `
    -Arguments @(
        "exec",
        "kafka",
        "kafka-console-consumer.sh",
        "--bootstrap-server",
        "kafka:9094",
        "--topic",
        $topicAlerts,
        "--from-beginning",
        "--max-messages",
        "$sampleCount",
        "--timeout-ms",
        "20000"
    )

$alertsResult.Stdout | Set-Content -LiteralPath $alertsValidationLogPath -Encoding UTF8
$alertsResult.Stderr | Add-Content -LiteralPath $alertsValidationLogPath -Encoding UTF8

Add-TerminalLog "Alerts validation command executed:"
Add-TerminalLog "docker exec kafka kafka-console-consumer.sh --bootstrap-server kafka:9094 --topic $topicAlerts --from-beginning --max-messages $sampleCount --timeout-ms 20000"
Add-TerminalLog "Alerts validation log:"
Add-TerminalLog $alertsValidationLogPath
Add-TerminalLog ""

Write-Host "Calculating latency metrics..."

$pythonCode = @"
import json
from datetime import datetime
from pathlib import Path

input_path = Path(r"$inputEventsPath")
alerts_path = Path(r"$alertsValidationLogPath")
results_path = Path(r"$latencyResultsPath")
summary_path = Path(r"$latencySummaryPath")

sample_count = $sampleCount
threshold_ms = $latencyThresholdMs

events = {}

for line in input_path.read_text(encoding="utf-8-sig").splitlines():
    if not line.strip():
        continue

    key, raw = line.split("|", 1)
    event = json.loads(raw)

    produced_at = event["produced_at"]
    produced_epoch = datetime.fromisoformat(produced_at).timestamp()

    events[event["transaction_id"]] = {
        "produced_at": produced_at,
        "produced_epoch": produced_epoch,
        "card_id": event["card_id"],
    }

rows = []

for line in alerts_path.read_text(encoding="utf-8-sig").splitlines():
    line = line.strip()

    if not line.startswith("{"):
        continue

    alert = json.loads(line)
    source_id = alert.get("source_transaction_id")

    if source_id not in events:
        continue

    triggered_at = float(alert["triggered_at"])
    latency_ms = (triggered_at - events[source_id]["produced_epoch"]) * 1000

    rows.append({
        "transaction_id": source_id,
        "card_id": events[source_id]["card_id"],
        "produced_at": events[source_id]["produced_at"],
        "triggered_at": triggered_at,
        "latency_ms": latency_ms,
        "alert_type": alert.get("alert_type"),
    })

rows.sort(key=lambda r: r["transaction_id"])

with results_path.open("w", encoding="utf-8", newline="") as f:
    f.write("transaction_id,card_id,produced_at,triggered_at,latency_ms,alert_type\n")
    for r in rows:
        f.write(f'{r["transaction_id"]},{r["card_id"]},{r["produced_at"]},{r["triggered_at"]},{r["latency_ms"]:.2f},{r["alert_type"]}\n')

latencies = [r["latency_ms"] for r in rows]

with summary_path.open("w", encoding="utf-8") as f:
    f.write("CP-10 - Latency summary\n\n")
    f.write(f"Samples expected: {sample_count}\n")
    f.write(f"Samples matched: {len(rows)}\n")

    if latencies:
        avg = sum(latencies) / len(latencies)
        f.write(f"Min latency ms: {min(latencies):.2f}\n")
        f.write(f"Avg latency ms: {avg:.2f}\n")
        f.write(f"Max latency ms: {max(latencies):.2f}\n")
        f.write(f"Criterion: average latency < {threshold_ms} ms\n")
        f.write(f"Result: {'PASSED' if avg < threshold_ms and len(rows) == sample_count else 'FAILED'}\n")
    else:
        f.write("No matching alerts found.\n")
        f.write("Result: FAILED\n")

print(summary_path.read_text(encoding="utf-8"))
"@

$pythonCode | python

$summaryContent = Get-Content -LiteralPath $latencySummaryPath -Encoding UTF8
$resultLine = $summaryContent | Where-Object { $_ -match "^Result:" } | Select-Object -Last 1
$passed = $resultLine -match "PASSED"

Add-TerminalLog "Latency results:"
Add-TerminalLog $latencyResultsPath
Add-TerminalLog "Latency summary:"
Add-TerminalLog $latencySummaryPath
Add-TerminalLog ""
$summaryContent | ForEach-Object { Add-TerminalLog $_ }

Write-Host ""
Write-Host "CP-10 execution summary"
Write-Host "-----------------------"
$summaryContent | ForEach-Object { Write-Host $_ }
Write-Host ""
Write-Host "Evidence files:"
Write-Host "- $terminalLogPath"
Write-Host "- $inputEventsPath"
Write-Host "- $producerOutputLogPath"
Write-Host "- $alertsValidationLogPath"
Write-Host "- $latencyResultsPath"
Write-Host "- $latencySummaryPath"

if ($passed) {
    Write-Host ""
    Write-Host "CP-10 validation: PASSED"
    Write-Host "Average end-to-end latency is below $latencyThresholdMs ms."
}
else {
    Write-Host ""
    Write-Warning "CP-10 validation: FAILED"
    Write-Warning "Average latency is above threshold or not all samples were matched."
}

Write-Host ""
Write-Host "Recommended manual screenshots:"
Write-Host "- docs/evidence/cp10_kafka_ui_alerts.png"
Write-Host "- docs/evidence/cp10_flink_job.png"
Write-Host ""
Write-Host "CP-10 script finished."